### ISSUE TITLE
skin system in launcher.

### ISSUE THREAD

**Issue by horriblejoseph** [AfoninZ/MultiMC5-Cracked#32]
I just tried to sign in to my ely.by account and I couldn't change to a different skin. I was stuck with the alex skin. Can you help me with this issue.

**Comment by maximmasterr** [comment]
Are you trying to change skin on ely.by or in launcher?

**Comment by horriblejoseph** [comment]
In launcher

**Comment by maximmasterr** [comment]
Currently this feature isn't implemented, try to change skin on ely.by

**Comment by maximmasterr** [comment]
I have just chosen random skin from ely.by and it works in game
![image](https://user-images.githubusercontent.com/25984188/121573565-12f0a800-ca2e-11eb-8af3-8a0f1179ebff.png)

**Comment by horriblejoseph** [comment]
I have a custom skin on Ely.by

**Comment by maximmasterr** [comment]
Is it showing up in the game?

**Comment by horriblejoseph** [comment]
No

**Comment by horriblejoseph** [comment]
No

**Comment by horriblejoseph** [comment]
[11:27:43] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:112) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:42) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:151) ~[authlib-2.3.31.jar:?]
	at dvo.a(SourceFile:672) [minecraft-1.17-client.jar:?]
	at dvo.<init>(SourceFile:431) [minecraft-1.17-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:179) [minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:77) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar:?]
	... 13 more

**Comment by horriblejoseph** [comment]
those are the errors

**Comment by horriblejoseph** [comment]
https://paste.ee/p/drDwg

**Comment by maximmasterr** [comment]
Try to recreate account and then relaunch launcher

**Comment by horriblejoseph** [comment]
I've done that 3 times already

**Comment by horriblejoseph** [comment]
I think it might be an issue with Java 16

**Comment by AfoninZ** [comment]
Trying to fix that bug in the new branch #feature-skins. So far skins show in launcher but not ingame for some reason.

**Comment by horriblejoseph** [comment]
I think it is because 1.17 need Java 16 and 1.16.5 works with the skins

**Comment by horriblejoseph** [comment]
Plus Java 16 might have a different coding language

**Comment by AfoninZ** [comment]
I don't quite get what you're talking about, I think the problem is 1.17 requiring a different version of authlib, though I'd ask @maximmasterr on this one. Also, issue comments don't work like SMS or chats - with every message there is an email sent to every maintainer. Editing your previous messages would be enough

**Comment by maximmasterr** [comment]
Minecraft versions since 1.16.4 are using authlib 2.x.x which is not affected with injection of authlib injector, i have opened https://github.com/yushijinhun/authlib-injector/issues/120, but i am thinking about creating another injector and integrating it inside multimc (like osenix launcher do)

**Comment by yushijinhun** [comment]
This might be related to yushijinhun/authlib-injector#121, which has been fixed in authlib-injector v1.1.36.

**Comment by maximmasterr** [comment]
Confirm, skins in minecraft 1.17 works as excepted, authlib update was automaticly downloaded

**Comment by horriblejoseph** [comment]
but it doesn't work on multiplayer

**Comment by yushijinhun** [comment]
> but it doesn't work on multiplayer
> 
> edit: how ever it does work in another cracked minecraft client at this link: https://mc-launcher.com/special/minecraft.html
> edit: worked with authlib jar modded in

I've tested Minecraft 1.17 + authlib-injector v1.1.37 (using ely.by as authentication server) + HMCL. It works well in multiplayer, so it might not be authlib-injector's problem.

**Comment by horriblejoseph** [comment]
I tried it on this the latest version of multimc cracked on my offline server and I was alex

**Comment by x673** [comment]
This is how the skin system in this launcher works, it automatically creates a UI and downloads the skin from crafatar. and it saves it to uuid.png file. but if you want to replace it with a different skin it will download it again. This issue can be fixed if the feature to download skins from crafatar in offline mode is turned off.

**Comment by horriblejoseph** [comment]
I've signed in with Ely.by and on the other launcher is works but doesn't here

**Comment by maximmasterr** [comment]
Could you send logs?

**Comment by horriblejoseph** [comment]
https://paste.ee/p/2Sf8S

**Comment by maximmasterr** [comment]
According to logs you are trying to use version 1.5.1, I have checked it in HMCL and skin doesn't display too. I think it is issue in authlib injector, but version 1.5.1 is too old. So just use popular new versions, like 1.7.10, 1.12.2, 1.16.3

**Comment by horriblejoseph** [comment]
I was using an April fool's version of Minecraft that was a fork of that version.

**Comment by yushijinhun** [comment]
> https://paste.ee/p/2Sf8S

```
[authlib-injector] [WARNING] An error occurred while processing request [/http/skins.minecraft.net/MinecraftSkins/horriblejoseph.png]
java.io.UncheckedIOException: java.io.IOException: Failed to fetch skin metadata for horriblejoseph
	at moe.yushi.authlibinjector.util.IOUtils.newUncheckedIOException(IOUtils.java:99)
	at moe.yushi.authlibinjector.httpd.LegacySkinAPIFilter.handle(LegacySkinAPIFilter.java:81)
	at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:132)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Failed to fetch skin metadata for horriblejoseph
	... 6 more
Caused by: java.io.UncheckedIOException: java.io.FileNotFoundException: https://account.ely.by/api/authlib-injector/api/profiles/minecraft
	at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryUUIDs(YggdrasilClient.java:65)
	at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryUUID(YggdrasilClient.java:80)
	at moe.yushi.authlibinjector.httpd.LegacySkinAPIFilter.handle(LegacySkinAPIFilter.java:75)
	... 4 more
Caused by: java.io.FileNotFoundException: https://account.ely.by/api/authlib-injector/api/profiles/minecraft
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at moe.yushi.authlibinjector.util.IOUtils.http(IOUtils.java:66)
	at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryUUIDs(YggdrasilClient.java:61)
	... 6 more
```

It seems that ely.by hasn't implemented `/api/profiles/minecraft` API, which might be the cause of the problem.

**Comment by horriblejoseph** [comment]
I get the same error on my offline server from the oldest to latest.

**Comment by maximmasterr** [comment]
TL Launcher (from mc-launcher) using authlib provided by ely by, our launcher and HMCL use authlib-injector and it fails

**Comment by horriblejoseph** [comment]
The only difference from what your doing what their doing is the method. I can't access premium servers on either client.

**Comment by maximmasterr** [comment]
So i don't understand what you are talking about:
- If you want to premium minecraft server(like Hypixel) ypu **need** premium minecraft account there is no workaround
- In launcher, in profile selector it shows my skin
- In game since version 1.7 skins are loaded and works

**Comment by horriblejoseph** [comment]
I was just suggesting to use the method that TL launcher uses because your experiencing more headache the way it is now.

**Comment by horriblejoseph** [comment]
The only reason I did anything with older versions is mods.

**Comment by horriblejoseph** [comment]
all I was doing replace the minecraft.jar with minecraft 2.0 blue edition and 1.5.1 works perfectly with it.

**Comment by erickskrauch** [comment]
@horriblejoseph, hi, I'm the author of the Ely.by project. I just deployed the [fix](https://github.com/elyby/accounts/commit/202099bf84eac16f37855e1526824c5e96fdbf95) that adds the missing route. Please, try again now.

**Comment by horriblejoseph** [comment]
It works now, thank you.

**Comment by horriblejoseph** [comment]
however multiplayer still has issues.

**Comment by horriblejoseph** [comment]
https://paste.ee/p/Ncvge
my multiplayer log

**Comment by maximmasterr** [comment]
Try to disable betacraft proxy, also could you send game host logs

**Comment by horriblejoseph** [comment]
I got the same issue without betacraft proxy

**Comment by horriblejoseph** [comment]
https://paste.ee/p/XXQUD
tried two different accounts on the same server both were alex

**Comment by yushijinhun** [comment]
Skins are not displayed if `online-mode` is off.

**Comment by horriblejoseph** [comment]
I couldn't join the server otherwise

**Comment by yushijinhun** [comment]
> I couldn't join the server otherwise

authlib-injector is also required on the server side. Add `-javaagent:authlib-injector.jar=ely.by` to your server commandline (before `-jar` option).

**Comment by horriblejoseph** [comment]
thank you for your help, it works now.
