### ISSUE TITLE
Unable to start minecraft after downloading assets

### ISSUE THREAD

**Issue by dickyharper** [AfoninZ/MultiMC5-Cracked#44]
### Operating System

Windows

### Description of bug

```
Params:
  --username  --version MultiMC5 --gameDir C:/Users/xxx/Desktop/MultiMC/instances/1.17/.minecraft --assetsDir C:/Users/xxx/Desktop/MultiMC/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/xxx/Desktop/MultiMC/injectors/authlib-injector-1.1.38.jar=http://localhost:52204, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 776


[authlib-injector] [INFO] Logging file: C:\Users\xxx\Desktop\MultiMC\instances\1.17\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.38
[authlib-injector] [INFO] Authentication server: http://localhost:52204
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
[authlib-injector] [INFO] Polyfill privileges API
Using onesix launcher.

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Callback Metafactory Transformer]
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:185)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.
Clipboard copy at: 28 Jun 2021 20:53:57 +0300
Clipboard copy at: 28 Jun 2021 20:53:58 +0300
Clipboard copy at: 28 Jun 2021 20:53:58 +0300
Clipboard copy at: 28 Jun 2021 20:53:59 +0300
Clipboard copy at: 28 Jun 2021 20:53:59 +0300

```

### Steps to reproduce

Unable to start minecraft 1.17 and 1.16 after assets are downloaded. Installed JRE version 8u291 x64.

### Suspected cause

Do I need a specific java version to run it?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Denisbg2011game** [comment]
download java 16 heres link https://download.oracle.com/otn-pub/java/jdk/16.0.1+9/7147401fd7354114ac51ef3e1328291f/jdk-16.0.1_windows-x64_bin.exe

**Comment by Denisbg2011game** [comment]
its this error need java 16 
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by dickyharper** [comment]
> 
> 
> download java 16 heres link https://download.oracle.com/otn-pub/java/jdk/16.0.1+9/7147401fd7354114ac51ef3e1328291f/jdk-16.0.1_windows-x64_bin.exe

It is working. Thank you for reply. 👍
